[package]
name = "prux"
version = "0.1.0"
authors = ["richerarc <richer.arc@gmail.com>", "sebaubin <sebastien.aubin91@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1.14"
tokio-tcp = "0.1.3"
tokio-io = "0.1.11"
futures = "0.1.25"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.4.10"
config = {version = "0.9.2", features = ["toml"]}
log = "0.4.6"
env_logger = "0.6.0"
clap = "2.32"
dns-lookup = "1.0.0"
hyper = "0.12.21"