[package]
name = "prux"
version = "1.1.1"
authors = ["richerarc <richer.arc@gmail.com>", "sebaubin <sebastien.aubin91@gmail.com>", "LucFauvel <luc.fauvel@hotmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1.22"
tokio-tcp = "0.1.3"
tokio-io = "0.1.12"
futures = "0.1.28"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.5"
config = {version = "0.9.3", features = ["toml"]}
log = "0.4.8"
env_logger = "0.6.2"
clap = "2.33.0"
dns-lookup = "1.0.1"
hyper = "0.12.33"
parking_lot = "0.9.0"
httparse = "1.3.4"
reqwest = {version = "0.9.20", features = ["rustls-tls"]}
base64 = "0.10.1"
bytes = "0.4.12"
crossbeam-channel = "0.3.9"
regex = "1.2.1"