FROM debian:stable-slim
LABEL maintainer "Devolutions Inc."

ENV USER=lucid

WORKDIR /etc/prux

RUN useradd -m -s /bin/bash ${USER}
RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl1.1 \
    ca-certificates \
    libcurl4-openssl-dev \
&& rm -rf /var/lib/apt/lists/*

USER ${USER}

COPY --chown=lucid:lucid prux .

EXPOSE 7479

RUN chmod +x ./prux

ENTRYPOINT [ "./prux" ]
