name: Production - Build & Publish

on:
  release:
    types: [published]

concurrency: prux_production

jobs:
  production:
    secrets: inherit
    uses: ./.github/workflows/shared.yml
    with:
      environment: production
      ref: ${{ github.event.release.tag_name }}
      tag: ${{ github.event.release.tag_name }}
