name: Production - Build & Publish
on:
  release:
    types: [published]

concurrency: prux_production

jobs:
  production:
    uses: ./.github/workflows/shared.yml
    with:
      environment: production
      ref: ${{ github.event.release.commit }}
      tag: ${{ github.event.release.tag_name }}
    secrets:
      DEVOLUTIONSBOT_TOKEN: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
