name: Production - Build & Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        default: master
        description: Commit SHA / branch to deploy
        required: true
        type: string
      tag:
        type: string
        description: Tag
        required: true

concurrency: prux_production

jobs:
  production:
    secrets: inherit
    uses: ./.github/workflows/shared.yml
    with:
      environment: production
      ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.event.release.tag_name }}
      tag: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.event.release.tag_name }}
