name: shared build & deploy workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      DEVOLUTIONSBOT_TOKEN:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
      GH_INFRA_PAT:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/**
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build prux
        run: |
          cargo build --bin prux --release

      - name: Archive dockerfile
        uses: actions/upload-artifact@v3
        with:
          name: dockerfile
          path: |
            Dockerfile.GH

      - name: Archive prux
        uses: actions/upload-artifact@v3
        with:
          name: prux
          path: |
            target/release/prux

  build_image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [build]

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: devolutionsbot
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: dockerfile/Dockerfile.GH
          context: .
          push: true
          tags: devolutions/prux:${{ inputs.tag }}

      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [build_image]
    if: ${{ inputs.environment == 'staging' }}

    steps:
      - name: Check out Devolutions/actions
        uses: actions/checkout@v3
        with:
          repository: Devolutions/actions
          ref: master
          token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}
          path: ./.github/workflows

      - name: Install Toolbox
        uses: ./.github/workflows/toolbox-install
        with:
          token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}

      - name: Trigger lucid deployment on staging
        run: dv github trigger-workflow -b master -r lucid -f staging.yml -i deployOnly=true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_INFRA_PAT }}
