name: Staging - Build & Publish

on:
  push:
    branches:
      - master

concurrency: prux_staging

jobs:
  staging:
    secrets: inherit
    uses: ./.github/workflows/shared.yml
    with:
      environment: staging
      ref: master
      tag: latest
